# Site settings
title: Essential UI
email: support@essentialui.com
description: A crafted collection of HTML, CSS and JS UI
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
permalink: /:categories/:title/
join: "https://gum.co/essential-ui"

# Build settings
markdown: kramdown
