# Site settings
title: "Essential UI"
email: "support@essentialui.com"
description: "A Crafted Free & Premium Collection of HTML, CSS and JS UI"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://reardestani.github.io/EssentialUI" # the base hostname & protocol for your site
permalink: /:title/
join: "https://gum.co/essential-ui"

# Build settings
markdown: kramdown
